spring:
  profiles:
    active: dev
  thymeleaf:
      cache : false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/creditindex?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    url: jdbc:mysql://172.17.20.205:3306/idridb?autoReconnect=true&useSSL=false&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    username: root
    password: Password01!
    #password: Mysql*ying13
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp





